development: &sandbox
  username: friend_1350256980_biz_api1.caixadeideias.com.br
  password: 1350257005
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AJFIPddNVo5YrVNPvfV3ggE.hbXk
  sandbox: true

test:
  <<: *sandbox

production: &production
  username: friend_1350256980_biz_api1.caixadeideias.com.br
  password: 1350257005
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AJFIPddNVo5YrVNPvfV3ggE.hbXk
  sandbox: true
